### ISSUE TITLE
Tracking of the implementation of shoutrrr

### ISSUE THREAD

**Issue by favonia** [favonia/cloudflare-ddns#632]
This is to track the technical details to implement #532 using shoutrrr.

- How to display all services in a RouterService (not all available services)?
- Should we set the title (or other params?)

# PRs and issues

- [x] Part 1: #633
- [x] Part 2: #640 
- [x] Part 3a: #762
- [x] Part 3b: #641
- [x] Part 4: #768
- [x] BUG: #770
- [x] Part 5: #772 
- [x] Part 6: #773

# Message

Current plan: These will be notified:

- [x] Starting of the program unless it's one-time
- [x] Configuration errors
- [ ] Use of deprecated settings (?)
- [x] IP detection error (every time!)
- [x] IP changes
- [x] Failures to update DNS records
- [x] Exiting of the program unless it's one-time

These will not be notified:

- [ ] Failure to ping monitors

**Comment by favonia** [comment]
Done!

**Comment by favonia** [comment]
Actually, I still need to update the documentation.

**Comment by favonia** [comment]
Really done now.
